"""Added shuffle options to Test model

Revision ID: 79949ce40b80
Revises: fde98b7df149
Create Date: 2024-10-16 19:20:18.864532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79949ce40b80'
down_revision = 'fde98b7df149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuffle_sentences', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shuffle_paragraphs', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('shuffle_paragraphs')
        batch_op.drop_column('shuffle_sentences')

    # ### end Alembic commands ###
