"""add vocabulary

Revision ID: e1ad58cf099c
Revises: 1f608820cd9f
Create Date: 2024-10-14 07:21:05.889809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ad58cf099c'
down_revision = '1f608820cd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('pronunciation_url', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vocabulary_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary')
    # ### end Alembic commands ###
