"""Add interval column to vocabulary

Revision ID: fde98b7df149
Revises: ae1863eb367e
Create Date: 2024-10-15 19:41:31.352676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fde98b7df149'
down_revision = 'ae1863eb367e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        # Add new columns with a default value to avoid IntegrityError for existing records
        batch_op.add_column(sa.Column('interval', sa.Float(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column('ease_factor', sa.Float(), nullable=False, server_default="2.5"))
        batch_op.add_column(sa.Column('learning_stage', sa.Integer(), nullable=False, server_default="1"))
        batch_op.drop_column('review_stage')

    # For databases that are not SQLite, you can drop the default afterwards
    if not isinstance(op.get_bind().dialect, sqlite.dialect):
        op.alter_column('vocabulary', 'interval', server_default=None)
        op.alter_column('vocabulary', 'ease_factor', server_default=None)
        op.alter_column('vocabulary', 'learning_stage', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_stage', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_column('learning_stage')
        batch_op.drop_column('ease_factor')
        batch_op.drop_column('interval')

    # ### end Alembic commands ###
